// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/messages/messages.proto

package go_micro_srv_messages

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Messages service

type MessagesService interface {
	Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (Messages_StreamService, error)
	PingPong(ctx context.Context, opts ...client.CallOption) (Messages_PingPongService, error)
}

type messagesService struct {
	c    client.Client
	name string
}

func NewMessagesService(name string, c client.Client) MessagesService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "go.micro.srv.messages"
	}
	return &messagesService{
		c:    c,
		name: name,
	}
}

func (c *messagesService) Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "Messages.Call", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messagesService) Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (Messages_StreamService, error) {
	req := c.c.NewRequest(c.name, "Messages.Stream", &StreamingRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	if err := stream.Send(in); err != nil {
		return nil, err
	}
	return &messagesServiceStream{stream}, nil
}

type Messages_StreamService interface {
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Recv() (*StreamingResponse, error)
}

type messagesServiceStream struct {
	stream client.Stream
}

func (x *messagesServiceStream) Close() error {
	return x.stream.Close()
}

func (x *messagesServiceStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *messagesServiceStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *messagesServiceStream) Recv() (*StreamingResponse, error) {
	m := new(StreamingResponse)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

func (c *messagesService) PingPong(ctx context.Context, opts ...client.CallOption) (Messages_PingPongService, error) {
	req := c.c.NewRequest(c.name, "Messages.PingPong", &Ping{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	return &messagesServicePingPong{stream}, nil
}

type Messages_PingPongService interface {
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Ping) error
	Recv() (*Pong, error)
}

type messagesServicePingPong struct {
	stream client.Stream
}

func (x *messagesServicePingPong) Close() error {
	return x.stream.Close()
}

func (x *messagesServicePingPong) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *messagesServicePingPong) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *messagesServicePingPong) Send(m *Ping) error {
	return x.stream.Send(m)
}

func (x *messagesServicePingPong) Recv() (*Pong, error) {
	m := new(Pong)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for Messages service

type MessagesHandler interface {
	Call(context.Context, *Request, *Response) error
	Stream(context.Context, *StreamingRequest, Messages_StreamStream) error
	PingPong(context.Context, Messages_PingPongStream) error
}

func RegisterMessagesHandler(s server.Server, hdlr MessagesHandler, opts ...server.HandlerOption) error {
	type messages interface {
		Call(ctx context.Context, in *Request, out *Response) error
		Stream(ctx context.Context, stream server.Stream) error
		PingPong(ctx context.Context, stream server.Stream) error
	}
	type Messages struct {
		messages
	}
	h := &messagesHandler{hdlr}
	return s.Handle(s.NewHandler(&Messages{h}, opts...))
}

type messagesHandler struct {
	MessagesHandler
}

func (h *messagesHandler) Call(ctx context.Context, in *Request, out *Response) error {
	return h.MessagesHandler.Call(ctx, in, out)
}

func (h *messagesHandler) Stream(ctx context.Context, stream server.Stream) error {
	m := new(StreamingRequest)
	if err := stream.Recv(m); err != nil {
		return err
	}
	return h.MessagesHandler.Stream(ctx, m, &messagesStreamStream{stream})
}

type Messages_StreamStream interface {
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*StreamingResponse) error
}

type messagesStreamStream struct {
	stream server.Stream
}

func (x *messagesStreamStream) Close() error {
	return x.stream.Close()
}

func (x *messagesStreamStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *messagesStreamStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *messagesStreamStream) Send(m *StreamingResponse) error {
	return x.stream.Send(m)
}

func (h *messagesHandler) PingPong(ctx context.Context, stream server.Stream) error {
	return h.MessagesHandler.PingPong(ctx, &messagesPingPongStream{stream})
}

type Messages_PingPongStream interface {
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Pong) error
	Recv() (*Ping, error)
}

type messagesPingPongStream struct {
	stream server.Stream
}

func (x *messagesPingPongStream) Close() error {
	return x.stream.Close()
}

func (x *messagesPingPongStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *messagesPingPongStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *messagesPingPongStream) Send(m *Pong) error {
	return x.stream.Send(m)
}

func (x *messagesPingPongStream) Recv() (*Ping, error) {
	m := new(Ping)
	if err := x.stream.Recv(m); err != nil {
		return nil, err
	}
	return m, nil
}
